language: java

services:
  - docker

jobs:
  include:
    - name: "AMD64/16"
      os: linux
      jdk: openjdk16
      arch: amd64

script: ./gradlew shadowJar

after_script:
  - docker compose build
  - docker tag supersonic_supersonic:latest ${{ secrets.DOCKER_REGISTRY }}/supersonic
  - docker push ${{ secrets.DOCKER_REGISTRY }}/supersonic