language: java

services:
  - docker

jobs:
  include:
    - name: "AMD64/16"
      os: linux
      jdk: openjdk16
      arch: amd64

script: ./gradlew shadowJar

after_script:
  - DOCKER_REGISTRY=$DOCKER_REGISTRY ./dockerscript.sh